-- RefrigeristaAPP — schema inicial
-- NÃO aplicar no Supabase da OficinaAPP. Este projeto exige banco próprio.

create extension if not exists pgcrypto;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  email text,
  document text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_sites (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  name text not null default 'Principal',
  address text,
  city text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.equipments (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  site_id uuid references public.customer_sites(id) on delete set null,
  type text not null,
  environment text,
  brand text,
  model text,
  serial_number text,
  capacity text,
  voltage text,
  refrigerant text,
  installed_at date,
  next_preventive_at date,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists equipments_customer_idx on public.equipments(customer_id);
create index if not exists equipments_serial_idx on public.equipments(serial_number);

create table if not exists public.work_orders (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity unique,
  customer_id uuid not null references public.customers(id),
  equipment_id uuid references public.equipments(id) on delete set null,
  status text not null default 'open'
    check (status in ('open','scheduled','in_service','waiting_customer','waiting_part','done','cancelled')),
  complaint text,
  diagnosis text,
  service_report text,
  scheduled_at timestamptz,
  opened_at timestamptz not null default now(),
  closed_at timestamptz,
  created_by uuid references auth.users(id),
  assigned_to uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists work_orders_customer_idx on public.work_orders(customer_id);
create index if not exists work_orders_equipment_idx on public.work_orders(equipment_id);
create index if not exists work_orders_status_idx on public.work_orders(status);

create table if not exists public.service_media (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  phase text not null default 'other'
    check (phase in ('before','during','after','equipment','label','other')),
  storage_path text not null,
  caption text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists service_media_order_idx on public.service_media(work_order_id);

create table if not exists public.work_order_items (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.work_orders(id) on delete cascade,
  kind text not null check (kind in ('service','material','other')),
  description text not null,
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  total numeric(12,2) generated always as (quantity * unit_price) stored,
  created_at timestamptz not null default now()
);

create table if not exists public.work_order_closings (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null unique references public.work_orders(id) on delete cascade,
  labor_total numeric(12,2) not null default 0 check (labor_total >= 0),
  material_total numeric(12,2) not null default 0 check (material_total >= 0),
  grand_total numeric(12,2) not null default 0 check (grand_total >= 0),
  payment_mode text not null default 'pending'
    check (payment_mode in ('pix','cash','card','invoiced','credit','pending')),
  payment_status text not null default 'pending'
    check (payment_status in ('paid','pending','partial')),
  amount_paid numeric(12,2) not null default 0 check (amount_paid >= 0),
  next_preventive_at date,
  warranty_until date,
  notes text,
  customer_name text,
  customer_confirmed boolean not null default false,
  signature_path text,
  signature_sha256 text,
  closed_by uuid references auth.users(id),
  closed_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  work_order_id uuid references public.work_orders(id) on delete cascade,
  equipment_id uuid references public.equipments(id) on delete cascade,
  actor_user_id uuid references auth.users(id),
  actor_type text not null default 'user'
    check (actor_type in ('user','customer','system')),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.customers enable row level security;
alter table public.customer_sites enable row level security;
alter table public.equipments enable row level security;
alter table public.work_orders enable row level security;
alter table public.service_media enable row level security;
alter table public.work_order_items enable row level security;
alter table public.work_order_closings enable row level security;
alter table public.activity_log enable row level security;

-- Políticas RLS, Storage e perfis serão definidos quando o Supabase próprio
-- do RefrigeristaAPP for criado. Até lá, este arquivo é somente a base do schema.
